version: '3.2'

services:
  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.1-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  controller:
    hostname: controller
    build: ./video-thumbnail-web-controller
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - rabbit
    environment:
      - RABBIT_HOST=rabbit
      - STORAGE_HOST=root

  thumbnail:
    build: ./video-to-gif-generator
    restart: unless-stopped
    depends_on:
      - rabbit
    volumes:
      - ./thumbnail_tmp:/bin/temp
    environment:
      - RABBIT_HOST=rabbit

  storage:
    build: ./simple-object-storage
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./bucket:/webapi/bucket
    environment:
      - DATABASE_HOST=database
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Sqrt(9)=3
      - DATABASE_NAME=backend-project-0

  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=backend-project-0
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Sqrt(9)=3
    volumes:
      - ./mysql-data:/var/lib/mysql:rw